### PR TITLE
configuration.rst: replace the ref-arch by 3nodes in the deployment file

### PR DESCRIPTION
**Pull request by goldyfruit**
The scenario have to be replaced by 3nodes.

### CODE REVIEW

**Comment by EmilienM** [comment]
Hello @goldyfruit , could you explain why you would like to replace it?
I changed it lately to show people our deployment should be tested on ref-arch, just as a example of real deployment. Let me know your motivation here, and we can fix it.
Thanks!

**Comment by goldyfruit** [comment]
@EmilienM 

It's to be consistent with the rest of the documentation:

```
Let’s create this file (in the example it will be named joe.yml) and describe its structure: * infra: infrastructure name (ex: 3nodes)
```

```
This is an example of a 3 nodes deployment: From the installation server, the configuration is generated by first creating this YAML file:
```

Regards.

**Comment by EmilienM** [comment]
I think we should use ref arch as the main example. What do you think? 
Also, please don't use github to contribute, but software factory. 
Thank you! 
Emilien

**Comment by goldyfruit** [comment]
@EmilienM Sure, we should definitely use ref-arch !
Any procedure about how to contribute on Software Factory ?

Thanks.

**Comment by EmilienM** [comment]
@goldyfruit http://softwarefactory.enovance.com/_docs/submitpatches.html

**Pull request closed without merging**
